# Generated by Django 3.0.7 on 2020-09-28 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='author',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='tag',
        ),
        migrations.AddField(
            model_name='quote',
            name='token',
            field=models.CharField(default='defaulttoken', max_length=100),
        ),
        migrations.AddField(
            model_name='quote',
            name='url',
            field=models.CharField(default='defaulturl', max_length=100),
        ),
    ]
